In [6]:
import pandas as pd

In [11]:
from matplotlib import animation
import matplotlib.pyplot as plt

In [10]:
ds1 = pd.read_excel(r"Proposal's Data Sets\ds1.xlsx")
ds1

,Year,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antarctica,Antigua and Barbuda,Argentina,...,United States,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Wallis and Futuna,Yemen,Zambia,Zimbabwe
0,1990,2603238,5444704,76737628,406704,5089864,51296,10992,219840,112079088,...,5113454675,3967289,103515759,65952,121823036,21298647,NaN,9520184,2407113,15551593
1,1991,2427366,4228256,78806834,406704,5064054,51296,14656,212512,117505744,...,5057930940,4527678,102920705,65952,115052176,21375535,NaN,9127376,2381811,15501544
2,1992,1379462,2495184,79883305,406704,5164449,54960,14656,208848,121230584,...,5167480847,5142888,110984327,62288,105576784,21466459,NaN,9873645,2424693,16713458
3,1993,1333055,2315648,81943970,410368,5748389,65952,14656,216176,117777485,...,5267343060,4439220,115617242,62288,123966331,22853002,NaN,8625426,2466007,16046611
4,1994,1281602,1912608,86147476,406704,3864521,65952,14656,216176,122229002,...,5358824048,4030404,107979978,62288,129531168,26168861,NaN,8982038,2393258,17393590
5,1995,1230463,2066496,94981417,425024,10948907,65952,3664,223504,127764859,...,5421502465,4557192,102663682,65952,132876193,28696697,NaN,10352088,2142313,15028392
6,1996,1164920,1993216,96786277,454336,10423993,69616,3664,238160,134762070,...,5610581589,5405165,105546009,84272,122338416,34206458,NaN,10526331,1837995,14908902
7,1997,1084127,1531552,87004706,465328,7347664,69616,3664,256480,137641464,...,5686464995,5513665,106629578,84272,133482705,44516863,NaN,11315914,2354102,13911984
8,1998,1029157,1744064,106621010,490976,7268420,76944,3664,271136,139451896,...,5731049595,5638758,118498913,80608,166803906,46791454,NaN,12064542,2278458,14131139
9,1999,809512,2975168,91668212,512960,9130235,80608,3664,282128,147285131,...,5804668919,6682218,121739198,84272,172562678,46889833,NaN,13723955,1777604,15727769
10,2000,757672,3004480,82221010,523952,9516064,87936,3664,293120,142358347,...,6010508353,5268017,120994017,84272,151869910,52600951,NaN,14475379,1784113,13818202
11,2001,797962,3220656,83780203,523952,9670938,95264,3664,296784,134003944,...,5904881595,5030443,122586352,87936,171975048,59654045,14656.0,16016834,1885603,12508722
12,2002,1051609,3748272,89406933,531280,12598124,95264,3664,329760,124392348,...,5946770566,4557757,127518315,84272,192746571,68499452,25648.0,15554371,1960891,11895839
13,2003,1185951,4231920,91048404,534944,8988970,102592,3664,351744,134631008,...,6011837495,4526888,125935969,84272,191457512,76047699,25648.0,17081395,2074413,10609583
14,2004,889167,4103680,87853359,560592,18700613,120912,7328,366400,157043391,...,6114006880,5564822,125118217,58624,151268097,87743442,25648.0,18647044,2104131,9428642
15,2005,1303267,4198944,106472836,575248,19005991,128240,7328,373728,161434200,...,6134521473,5726669,116576172,58624,163822999,94693883,29312.0,19794359,2242543,10698489
16,2006,1635378,3843536,100202857,545936,22101650,142896,7328,384720,174608992,...,6051668046,6597095,119364938,47632,160160226,98625742,29312.0,21084874,2231118,10365461
17,2007,2268605,3828880,108401946,538608,24977271,150224,10992,406704,174245760,...,6131004158,5947501,119113158,98928,149924084,100362015,29312.0,20719069,2294254,9835161
18,2008,4199530,4272224,109031978,538608,25486267,150224,0,417696,188106000,...,5914077766,8201629,123038846,95264,168690196,113326892,21984.0,22025267,2553028,7720014
19,2009,6739976,4253904,120184849,516624,27564973,146560,0,443344,178949200,...,5478209686,7946771,106251774,120912,169572855,123442875,29312.0,24251389,2940336,5476316
20,2010,8397779,4448096,117813010,516624,28864503,150224,0,454336,186733136,...,5675786435,6297960,103336000,120912,184084056,138585135,29312.0,23150591,3120300,7878316
21,2011,12105788,5030672,119807538,490976,30329742,142896,0,443344,190273774,...,5540173478,7652644,112704612,131904,175944973,151230628,25648.0,20190194,3372367,9743983
22,2012,10218514,4667936,128110556,487312,33800624,142896,0,458000,191714848,...,5338698344,8591791,114891110,113584,182224419,142552003,25648.0,18268332,4165843,7882889
23,2013,8440766,4928080,132435012,476320,33228583,117248,0,461664,190133373,...,5474256770,7492373,109473193,106256,207424913,149220090,21984.0,24976297,4416159,11836254
24,2014,7774340,5620576,142528719,461664,33296311,139232,0,461664,188657102,...,5522807202,6684323,104953028,153888,186708214,169006166,21984.0,24215664,4876557,11905687
25,2015,7904133,4495728,149682942,465328,33621246,153888,0,479984,192405960,...,5371770557,6725465,101412072,131904,180124211,193003686,21984.0,12806287,5097951,12225821
26,2016,6744628,4492064,148928670,468992,31403799,153888,0,490976,190977194,...,5248023931,6520440,108168748,146560,169476933,192765567,25648.0,10426915,5659098,10737567
27,2017,6859825,5301808,154935572,465328,28420359,142896,0,490976,187804729,...,5207751278,6162573,107153232,139232,161535508,195249310,25648.0,9950980,6517240,9581633
28,2018,8344829,4733888,161486543,494640,24375801,142896,0,498304,181099627,...,5375490614,6570970,114732232,175872,120176685,223717789,25648.0,9983747,7313113,11854367
29,2019,12146674,4863450,166641950,501848,23486822,139475,0,486373,167565587,...,5255816207,6583985,114198988,181284,99175323,260312093,26437.0,10020408,7047207,10949084